// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shortening.API.Contexts;

#nullable disable

namespace Shortening.API.Migrations
{
    [DbContext(typeof(ShorteningDbContext))]
    [Migration("20230604232849_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shortening.API.Entities.UrlShorteningEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OriginalUrl")
                        .HasColumnType("nvarchar(MAX)")
                        .HasColumnName("original_url");

                    b.Property<string>("ShortenedUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar")
                        .HasColumnName("shortened_url");

                    b.HasKey("Id");

                    b.ToTable("url_shortenings", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
